version: "3.9"

services:
  megh-pipeline:
    build: 
      context: .
      cache_from:
         - megh-pipeline:latest
    container_name: megh-pipeline
    user: ubuntu
    volumes:
      - .:/megh-pipeline
    working_dir: /megh-pipeline
    env_file:
      - .env
    command: uv run dvc repro