version: "3.9"

services:
  megh-pipeline:
    build: .
    container_name: megh-pipeline
    user: ubuntu
    volumes:
      - .:/megh-pipeline
    working_dir: /megh-pipeline
    env_file:
      - .env
    command: >
      bash -c "uv  run dvc repro"