stages:
  data:
    cmd: >
      python stage_01_data.py 
      --data_config config/data.yaml 
      --database_config config/db.yaml 
      --feature_config config/features.yaml
    outs:
      - artifacts/features.parquet
      - artifacts/data.pkl
      - artifacts/run_id.txt
    deps:
    - config/data.yaml
    - config/db.yaml
    - config/features.yaml

  train_eval:
    cmd: >
      python stage_02_train_eval.py 
      --ml_config config/ml.yaml 
      --search_space config/search_spaces.yaml 
      --data_config config/data.yaml 
      --database_config config/db.yaml 
      --feature_config config/features.yaml
    deps:
      - artifacts/data.pkl
      - artifacts/run_id.txt
      - config/data.yaml
      - config/db.yaml
      - config/features.yaml
      - config/ml.yaml
      - config/search_spaces.yaml 
    outs:
      - artifacts/train_dataset.parquet
      - artifacts/test_dataset.parquet
      - artifacts/predictions.parquet
      - artifacts/shap_values.parquet
      - artifacts/shap_summary.png